<div class="header">
    <h1>Modules</h1>
    <?php echo $this->showMessages(); ?>
</div>
<div class="content">
    <a href="<?php echo $this->url('resource-module-admin-create'); ?>">Neu anlegen</a>
    <?php if (count($this->moduleAdminRead)): ?>
        <table class="table table-striped">
            <thead>
            <tr>
                <th><?php echo $this->translate('ID'); ?></th>
                <th><?php echo $this->translate('Name'); ?></th>
                <th><?php echo $this->translate('Description'); ?></th>
                <th><?php echo $this->translate('Ist Aktiv'); ?></th>
                <th><?php echo $this->translate('Actions'); ?></th>
            </tr>
            </thead>
            <tbody>
        <?php foreach ($this->moduleAdminRead as $moduleAdminRead): ?>
                <tr>
                    <td>
                        <?php echo $this->escapeHtml($moduleAdminRead->getId()); ?>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($moduleAdminRead->getName()); ?>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($moduleAdminRead->getDescription()); ?>
                    </td>
                    <td>
                        <?php echo $this->yesNo($this->escapeHtml($moduleAdminRead->getIsActive())); ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->url('resource-module-admin-update') . $moduleAdminRead->getId(); ?>">Update</a> |
                        <a href="<?php echo $this->url('resource-module-admin-delete') . $moduleAdminRead->getId(); ?>">Delete</a>
                    </td>
                </tr>
        <?php endforeach ?>
    </tbody>
    <?php endif ?>
    </table>
</div>


